
<form method="post">
    <?php if( !isset($this->authorizedList) ) : ?>
        <fieldset>
            <legend>Login</legend>
            <input type="text" name="login_email" placeholder="Email Address" />
            <input type="password" name="login_password" placeholder="Password" />
        </fieldset>
        <fieldset>
            <legend>Sign Up</legend>
            <input type="text" name="signup_email" placeholder="Email Address" />
            <input type="password" name="signup_password" placeholder="Password" />
            <input type="password" name="signup_confirm" placeholder="Confirm Password" />

            <!-- TODO: Add required fields for complete profile information; they may be added to the -->
        </fieldset>
    <?php endif;?>
        <!-- TODO: Upon submit of sign-up a pop-up is needed for confirmation email etc. -->
        <label> Authorize <?php echo $this->escapeHtml($this->clientId) ?>?</label><br />
        <input type="submit" name="authorized" value="yes">
        <input type="submit" name="authorized" value="no">
</form>
